<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Package extends \App\Entity\Package implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'limit_report', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'number_app', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'userPackages'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'limit_report', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'number_app', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Package' . "\0" . 'userPackages'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Package $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Package
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice(string $price): \App\Entity\Package
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getLimitReport(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLimitReport', []);

        return parent::getLimitReport();
    }

    /**
     * {@inheritDoc}
     */
    public function setLimitReport(int $limit_report): \App\Entity\Package
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLimitReport', [$limit_report]);

        return parent::setLimitReport($limit_report);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberApp(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberApp', []);

        return parent::getNumberApp();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberApp(int $number_app): \App\Entity\Package
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberApp', [$number_app]);

        return parent::setNumberApp($number_app);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(bool $status): \App\Entity\Package
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserPackages(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPackages', []);

        return parent::getUserPackages();
    }

    /**
     * {@inheritDoc}
     */
    public function addUserPackage(\App\Entity\UserPackage $userPackage): \App\Entity\Package
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserPackage', [$userPackage]);

        return parent::addUserPackage($userPackage);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserPackage(\App\Entity\UserPackage $userPackage): \App\Entity\Package
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserPackage', [$userPackage]);

        return parent::removeUserPackage($userPackage);
    }

}
