#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login:
    path: /login
    controller: App\Controller\SecurityController::login
logout:
  path: /logout
  controller: App\Controller\SecurityController::logout
register:
    path: /register
    controller: App\Controller\SecurityController::register
validation_eamil:
  path: /validation_eamil
  controller: App\Controller\SecurityController::validation_eamil
validation:
  path: /validation
  controller: App\Controller\SecurityController::validation
validation_password:
  path: /validation_password
  controller: App\Controller\SecurityController::validation_password


index:
    path: /
    controller: App\Controller\IndexController::index
request_for_log:
  path: /logger
  controller: App\Controller\IndexController::logger

dashbord:
  path: /dashbord
  controller: App\Controller\Users\UsersController::dashbord
buy_package:
  path: /dashbord/buy_package{id?}
  controller: App\Controller\Users\UsersController::buy_package




add_app:
  path: /dashbord/add_app
  controller: App\Controller\Users\ApplicationController::add_app
add_package_app:
  path: /dashbord/add_package_app
  controller: App\Controller\Users\ApplicationController::add_package_app
change_token:
  path: /dashbord/buy_package/change_token
  controller: App\Controller\Users\ApplicationController::change_token
list_app:
  path: /dashbord/list_app
  controller: App\Controller\Users\ApplicationController::list_app
remove_app:
  path: /dashbord/list_app/remove_app{id}
  controller: App\Controller\Users\ApplicationController::remove_app
edit_app:
  path: /dashbord/list_app/edit_app/{id?}
  controller: App\Controller\Users\ApplicationController::edit_app
searching_app:
  path: /dashbord/list_app/searching_app
  controller: App\Controller\Users\ApplicationController::searching_app


list_packages:
  path: /dashbord/list_packages
  controller: App\Controller\Users\PackagesController::list_packages
add_packages:
  path: /dashbord/add_packages/{name_app?}
  controller: App\Controller\Users\PackagesController::add_packages
edit_packages:
  path: /dashbord/edit_packages{id?}
  controller: App\Controller\Users\PackagesController::edit_packages
delete_packages:
  path: /dashbord/delete_packages{id?}
  controller: App\Controller\Users\PackagesController::delete_packages
bought_package:
  path: /dashbord/bought_package/{name_package?}
  controller: App\Controller\Users\PackagesController::bought_package
searching_package:
  path: /dashbord/searching_package
  controller: App\Controller\Users\PackagesController::searching_package
searching_bought_package:
  path: /dashbord/searching_bought_package
  controller: App\Controller\Users\PackagesController::searching_bought_package


Log_deatil_type:
  path: /dashbord/Log_deatil_type/{type}
  controller: App\Controller\Users\LoggerController::Log_deatil_type
detail_log:
  path: /dashbord/detail_log/{id}
  controller: App\Controller\Users\LoggerController::detail_log
getLogs:
  path: /dashbord/getLogs
  controller: App\Controller\Users\LoggerController::getLogs

list_article:
  path: /dashbord/list_article
  controller: App\Controller\ArticlesController::list_article
add_article:
  path: /dashbord/add_article
  controller: App\Controller\ArticlesController::add_article
