<?php

namespace ContainerWXd5zf7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_72IH7xBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.72IH7xB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.72IH7xB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'app' => ['privates', 'App\\Services\\ApplicationServices', 'getApplicationServicesService', true],
            'logger' => ['privates', 'App\\Services\\Logger\\LoggerServices', 'getLoggerServicesService', true],
        ], [
            'app' => 'App\\Services\\ApplicationServices',
            'logger' => 'App\\Services\\Logger\\LoggerServices',
        ]);
    }
}
