<?php

namespace ContainerWXd5zf7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RlLJ4_QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RlLJ4.q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RlLJ4.q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categotyServices' => ['services', 'App\\Services\\Category\\CategotyServices', 'getCategotyServicesService', true],
        ], [
            'categotyServices' => 'App\\Services\\Category\\CategotyServices',
        ]);
    }
}
