<?php

namespace ContainerWXd5zf7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationServicesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\ApplicationServices' shared autowired service.
     *
     * @return \App\Services\ApplicationServices
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'ApplicationServices.php';

        return $container->privates['App\\Services\\ApplicationServices'] = new \App\Services\ApplicationServices(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
