<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEqeaOGa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEqeaOGa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEqeaOGa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEqeaOGa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEqeaOGa\App_KernelDevDebugContainer([
    'container.build_hash' => 'EqeaOGa',
    'container.build_id' => '4ccf5f7c',
    'container.build_time' => 1630822775,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEqeaOGa');
