<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxkGjlo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxkGjlo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSxkGjlo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSxkGjlo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSxkGjlo\App_KernelDevDebugContainer([
    'container.build_hash' => 'SxkGjlo',
    'container.build_id' => '49a08e51',
    'container.build_time' => 1633877978,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxkGjlo');
