<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWXd5zf7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWXd5zf7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWXd5zf7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWXd5zf7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWXd5zf7\App_KernelDevDebugContainer([
    'container.build_hash' => 'WXd5zf7',
    'container.build_id' => '0a891d11',
    'container.build_time' => 1630753692,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWXd5zf7');
